we are closing the issue 8 and 25
amepproject/amep pull request #92
Opened 2024-12-06 12:07 UTC by suvendu266

please check the merge request.

Suvendu

2024-12-18 14:40 UTC, kay-ro requested changes
minor changes required.
please address the second round of comments as well

2024-12-18 14:40 UTC, kay-ro commented on amep/utils.py
The Notes are for the users to read. Not internal development-comments. Could you please adapt the notes?
secondly, please add an appropriate comment to the sqiso function for the qmin.

2024-12-18 14:40 UTC, kay-ro commented on amep/plot.py
could you please simplify the example?
for example:
1. plot a linear function from 0 to 10.
2. add one annotation arrow.

2024-12-18 14:40 UTC, kay-ro commented on amep/utils.py
the qmin is not set to this default value in domain_length. please correct the comment. (it is expected that the q values are "correct" already)

2024-12-18 14:40 UTC, kay-ro commented on amep/spatialcor.py
Please specify the comment. qmin is not mentioned or defined anywhere beforehand.
Also mention what the distance between q values is and so on...

2024-12-18 14:40 UTC, kay-ro commented on amep/plot.py
please modify the first example to a minimum working example.

0. import amep
1. as specified before, plot a linear function from 0 to 10.
2. add one annotation arrow.

2025-03-09 15:09 UTC, hechtprojects approved these changes

2025-03-09 15:09 UTC, kay-ro commented on amep/utils.py
fixed by Lukas Hecht

2025-03-09 15:11 UTC, merged