Temperatures
amepproject/amep pull request #96
Opened 2024-12-11 17:32 UTC by hechtprojects

Tkin, Tkin4, Tconf, and Tosc implemented. Please test the corresponding evaluate classes in detail:

- [ ] `amep.evaluate.Tkin`
- [ ] `amep.evaluate.Tkin4`
- [ ] `amep.evaluate.Tosc`
- [ ] `amep.evaluate.Tconf`

If they run without any errors, please merge into develop. The new features can then be included in the next minor release.

2024-12-18 15:07 UTC, kay-ro requested changes
when running the 

```
path="examples/data/lammps.h5amep"
traj= amep.load.traj(path)
tkin = amep.evaluate.Tkin(traj, nav=traj.nframes)
tkin4 = amep.evaluate.Tkin4(traj, nav=traj.nframes)
tosc = amep.evaluate.Tosc(traj, .1, nav=traj.nframes)
tconf = amep.evaluate.Tconf(traj,amep.utils.dr_wca, amep.utils.dr2_wca, nav=traj.nframes)
```

the shape of `tkin4.frames` is not just (nframes) but (nframes, nparticles) with all the same values.

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +        super(Tkin4, self).__init__()
super type causes error. please fix. `Tosc`?

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            self, traj: ParticleTrajectory, drU, dr2U,
please add type hints for `drU` and `dr2U.` (callable)

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            Function value for each frame.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            Times at which the function is evaluated.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            Time-averaged spatial velocity correlation function.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +        correlation function has been evaluated.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +        correlation function has been evaluated.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            Time-averaged spatial velocity correlation function.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            Times at which the function is evaluated.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +        correlation function has been evaluated.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            Time-averaged spatial velocity correlation function.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +        function is evaluated.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +            Time-averaged spatial velocity correlation function.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +        function is evaluated.
fix description

2024-12-18 15:07 UTC, kay-ro commented on amep/evaluate.py
> +        Spatial velocity correlation function for each frame.
fix description

2025-02-22 11:25 UTC, hechtprojects commented
The bugs and descriptions are fixed now.

2025-02-24 13:14 UTC, kay-ro approved these changes
Thanks!

2025-02-24 13:55 UTC, merged